# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/NLP',
                'doc_host': 'https://nextrick.github.io',
                'git_url': 'https://github.com/nextrick/NLP',
                'lib_path': 'NLP'},
  'syms': {'NLP.core': {'NLP.core.foo': ('core.html#foo', 'NLP/core.py')}}}
